// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CycleController from "./cycle_controller"
application.register("cycle", CycleController)

import SoundController from "./sound_controller"
application.register("sound", SoundController)

import WarpController from "./warp_controller"
application.register("warp", WarpController)
